# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    -   id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
    -   id: pyupgrade
        args: ["--py36-plus"]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5  # or specific git tag
  hooks:
    - id: forbid-binary
      exclude: (?x)^tests/data/.*\.exe$     # allow for test data
    - id: markdownlint # Configure in .mdlrc
    - id: shellcheck

- repo: https://github.com/IamTheFij/docker-pre-commit
  rev: v2.0.0
  hooks:
        - id: docker-compose-check
        - id: hadolint
          args: [ --ignore, DL3007,  # we use latest to build the debug image
             --ignore, DL3008 ]  # we don't pin versions (yet?)

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
    - id: bandit
      args: [ --baseline, .bandit-baseline.json]
      exclude: tests/

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args: [--in-place]

- repo: https://gitlab.com/iamlikeme/nbhooks
  rev: "1.0.0"
  hooks:
  - id: nb-ensure-clean
    #args: [--meta, ExecuteTime]  # Optional blacklist of metadata keys (you can use regex)

- repo: https://github.com/Yelp/detect-secrets
  rev: "v1.1.0"
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/tests/.*
