FROM amazonlinux:latest

# improvements:
#   - use non-root user (but set home not to bind mount)

WORKDIR /usr/src/app

# get the tools we need (vscode needs tar)
RUN yum install -y python-devel python2-pip gcc zip findutils git tar
# pip 10 doesn't uninstall chardet, which we need upgraded
RUN pip install --disable-pip-version-check --upgrade "pip<10" setuptools

# sort out osslsigncode requirements
# RUN yum install -y libgsf autoconf automake curl-devel make rpm-build openssl11 openssl11-devel openssl11-static ; \
# ln lib64/pkgconfig/*11.pc to *.pc
# yum install yum-utils
# yumdownloader --source curl
# edit spec to enable static
    # rpm -i ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home%3A/danimo/CentOS_7/src/osslsigncode-1.7.1-5.3.src.rpm && \
    # cd ~/rpmbuild && \
    # rpmbuild -bb SPECS/osslsigncode.spec && \
    # rpm -i RPMS/x86_64/osslsigncode-1.7.1-5.3.x86_64.rpm

## # Dev requirements
## COPY requirements-dev.txt ./
## RUN pip install -r requirements-dev.txt
##
## # Cache runtime requirements which are used during install, but install them so
## # we can use this container for development
## COPY requirements.txt ./
## RUN pip download --requirement requirements.txt
## RUN pip install  --requirement requirements.txt
##
## # now that everything is installed system wide, lets create a user, and
## # set their home dir to mode 777, the mapped user can install there
## RUN useradd --no-log-init fake \
##     && mkdir /home/fxsv \
##     && chmod -R a+rwX /home/*
##
## # assume mount at /home/fxsv
## CMD cd /home/fxsv ; pip install --user -e .[cli] ; PATH=/home/fake/.local/bin:$PATH bash -i
